const iconExperience = [
  {
    id: 1,
    cardImg: "media/images/Janhvi Kapoor.webp",
    cardHeading: "Live like Bollywood star Janhvi Kapoor",
    hostName: "Hosted by Janhvi Kapoor",
    cardInfo: "Sold out",
  },
  {
    id: 2,
    cardImg: "media/images/Musee.webp",
    cardHeading: "Open the Olympic Games at Musee d'O...",
    hostName: "Hosted by Mathieu Lehanneur",
    cardInfo: "Sold out",
  },
  {
    id: 3,
    cardImg: "media/images/Wake Up In.webp",
    cardHeading: "Wake up in the Musee d'Orsay",
    hostName: "Hosted by Mathieu Lehanneur",
    hostName: "Sold out",
  },
  {
    id: 4,
    cardImg: "media/images/Inside Out 2.webp",
    cardHeading: "Make a core memories with Inside Out 2",
    hostName: "Hosted by Wendy and Lisa",
    cardInfo: "Sold out",
  },
  {
    id: 5,
    cardImg: "media/images/Supersuit.jpeg",
    cardHeading: "Design you Incredibles Supersuit",
    hostName: "Hosted by Edna Mode",
    cardInfo: "Sold out",
  },
  {
    id: 6,
    cardImg: "media/images/Feid.webp",
    cardHeading: "Go on tour with Feid",
    hostName: "Hosted by Feid",
    cardInfo: "Sold out",
  },
  {
    id: 7,
    cardImg: "media/images/Khaby Lame.webp",
    cardHeading: "Game wiht Khaby Lame",
    hostName: "Hosted by Khaby Lame",
    cardInfo: "Sold out",
  },
  {
    id: 8,
    cardImg: "media/images/Crash at.webp",
    cardHeading: "Crash at the X-Mansion",
    hostName: "Hosted by Jubilee",
    cardInfo: "Sold out",
  },
  {
    id: 9,
    cardImg: "media/images/Ferrari Museum.jpeg",
    cardHeading: "Spend the night in the Ferrari Museum",
    hostName: "Hosted by Marc Gene",
    cardInfo: "Sold out",
  },
  {
    id: 10,
    cardImg: "media/images/Drift Off.webp",
    cardHeading: "Drift off in the Up House",
    hostName: "Hosted by Wendy and Lisa",
    cardInfo: "Sold out",
  },
  {
    id: 11,
    cardImg: "media/images/Shrek's Swamp.webp",
    cardHeading: "Shrek's Swamp",
    hostName: "Hosted by Donkey",
    cardInfo: "Sold out",
  },
  {
    id: 12,
    cardImg: "media/images/Barbie's Malibu DreamHouse.webp",
    cardHeading: "Barbie's Malibu DreamHouse, Ken's Way",
    hostName: "Hosted by Ken",
    cardInfo: "Sold out",
  },
  {
    id: 13,
    cardImg: "media/images/Ted Lasso's.webp",
    cardHeading: "Ted Lasso's Favorite Pub",
    hostName: "Hosted by Mae",
    cardInfo: "Sold out",
  },
  {
    id: 14,
    cardImg: "media/images/Houseplant Retreat.webp",
    cardHeading: "Houseplant Retreat",
    hostName: "Hosted by Seth Rogen",
    cardInfo: "Sold out",
  },
  {
    id: 15,
    cardImg: "media/images/Home Alone Holiday.jpeg",
    cardHeading: "Home Alone'Holiday",
    hostName: "Hosted by Buzz",
    cardInfo: "Sold out",
  },
  {
    id: 16,
    cardImg: "media/images/Blockbuster.webp",
    cardHeading: "The Last Blockbuster",
    hostName: "Hosted by Sandi",
    cardInfo: "Sold out",
  },
];

export default iconExperience;